package rs.ac.bg.fon.communication;

import java.io.Serializable;

public enum Operation implements Serializable {
    LOGOVANJE,
    ZAPAMTI_PUTNIKA,
    PRONADJI_PUTNIKE,
    UCITAJ_PUTNIKA,
    OBRISI_PUTNIKA,
    PRONADJI_PUTNOVANJA,
    UCITAJ_PUTOVANJE,
    ZAPAMTI_PUTOVANJE,
    ZAPAMTI_REZERVACIJU,
    PRONADJI_REZERVACIJE,
    UCITAJ_REZERVACIJE,
    OBRADI_REZERVACIJU,
    STORNIRAJ_REZERVACIJU,
    UCITAJ_PUTOVANJA_PUTNIKA,
    UCITAJ_LISTU_GRADOVA,
    UCITAJ_LISTU_PUTNIKA,
    UCITAJ_LISTU_PUTOVANJA,
    UCITAJ_LISTU_TERMINA;
}
